disease_ontology/disease_ontology/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.views.generic.simple import direct_to_template, redirect_to

from disease_ontology.apps.news.views import news
from disease_ontology.apps.links.views import links
from disease_ontology.apps.content.views import (welcome_content, 
                metadata_content, search_content, visualize_content, contact)

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', direct_to_template, {
        'template': 'index.html', 
        'extra_context': {
             'title': 'Disease Ontology - Institute for Genome Sciences @ University of Maryland',
             'ext': True,
         }
    }, "home"),
    url(r'^term/(.+)/$', metadata_content, name="metadata"),
    url(r'^search$', search_content, name="search"),
    url(r'^visual/(.+)/(.+)/$', visualize_content, name="visual"),
    url(r'^news/$', news, name="news"),
    url(r'^downloads/$', direct_to_template, {
        'template': 'downloads.html',
        'extra_context': {
            'title': 'Disease Ontology - Institute for Genome Science - Downloads',
            'ext': False
        }
    }, "downloads"),
    url(r'^link/$', links, name="links"),
    url(r'^about/$', direct_to_template, {
        'template': 'about.html',
        'extra_context': {
            'title': 'Disease Ontology - Institute for Genome Sciences - About',
            'ext': False
        }
    }, "about"),
    url(r'^support/$', direct_to_template, {
        'template': 'support.html',
        'extra_context': {
            'title': 'Disease Ontology - Institute for Genome Sciences - Support',
            'ext': False
        }
    }, "support"),
    url(r'^contact/$', contact, name="contact"),
    url(r'^contact/thanks/$', direct_to_template, {
        'template': 'thanks.html',
        'extra_context': {
            'title': 'Disease Ontology - Institute for Genome Sciences - Contact',
            'ext': False
        }
    }, "thanks"),
    url(r'^tutorial/$', direct_to_template, {
        'template': 'tutorial.html',
        'extra_context': {
            'title': 'Disease Ontology - Institute for Genome Sciences - Tutorial',
            'ext': False
        }
    }, "tutorial"),
    (r'^welcome/$', welcome_content),
    (r'^blank_results/$', direct_to_template, {
        'template': 'content/blank_results.html',
        'extra_context': {
            'title': 'Disease Ontology - Institute for Genome Sciences - Links',
            'ext': False,
        }
    }),
    (r'^arbor_key/$', direct_to_template, { 'template': 'content/key_tbl.html' }),
    
    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
)

disease_ontology/disease_ontology/apps/content/views.py
import logging
import sys

from neo4jdo import Neo4jDO
from do_lucene_search import search_lucene_index
from math import ceil, floor
from recaptcha.client import  captcha

from django import forms
from django.http import HttpResponse, HttpResponseRedirect
from django.template import Context
from django.template.loader import get_template
from django.shortcuts import render_to_response
from django.conf import settings
from django.core.mail import send_mail
from django.views.decorators.csrf import csrf_exempt

from disease_ontology.apps.news.models import NewsPost

logger = logging.getLogger(__name__)

class ContactForm(forms.Form):
    """
    A forms to get in touch with an administrator for the Disease Ontology
    website
    """
    FEEDBACK_CHOICES = (
        ('Comment', 'Comment'),
        ('Suggestion', 'Suggestion'),
        ('Bug', 'Bug'),
    )
    feedbackType = forms.ChoiceField(widget=forms.Select, choices=FEEDBACK_CHOICES, label="Feedback Type:")
    senderName = forms.CharField(label="Name:")
    senderEmail = forms.EmailField(label="Email:")

    message = forms.CharField(label="Message:", widget=forms.Textarea)

def welcome_content(request):
    """
    Our welcome tab panel which will contain news and update 
    informsation
    """
    template = get_template('content/welcome_content.html')

    variables = Context({
        'news_list': NewsPost.objects.all()[:3]
    })

    output = template.render(variables)
    return HttpResponse(output)

def metadata_content(request, doid_term):
    """
    Load our term metadata into our ExtJS TabPanel as a fragment. This function
    queries the Neo4j database using our Neo4j wrapper class and pulls down. 
    Node metadata is retrieved and the id and name are explicitly pulled out
    and removed from the metadata keys list. The rest of the metadata is stored
    in a list of tuples of key, value to be passed to the template.
    """
    # A list of elements we don't want included in the secondary_meta list
    primary_meta = settings.PRIMARY_METADATA
    graph_db = Neo4jDO(settings.NEO4J_URL)

    try:
        node = graph_db.get_node_by_ontologyid(doid_term)
    except IndexError as e:
        logger.exception("Term %s not found in database" % doid_term)
        return render_to_response('404.html', {'error_msg': error_msg})

    neo4j_id = node.id
    term_id = node.get('id')
    name = node.get('name')
    definition = node.get('definition', None)

    relationships = graph_db.get_formatted_node_relationships(node)

    secondary_metadata = []
    for key in [x for x in node.properties.keys() if x not in primary_meta]:
        value = node.get(key)
        secondary_metadata.append( (key, value) )


    template = get_template('content/metadata_content.html')
    variables = Context({
        'neo4j_id': neo4j_id,
        'term_id': term_id,
        'term_name': name,
        'term_definition': definition,
        'secondary_meta': secondary_metadata,
        'relationships': relationships,
    })

    output = template.render(variables)
    return HttpResponse(output)

def search_content(request):
    """
    Searches through the lucene index and generates a page displaying all 
    all search results.
    """
    results = []

    index_metadata = settings.OBO_INDEX_METADATA
    index_dir = settings.LUCENE_INDEX
    records_per_page = settings.RECORDS_PER_PAGE
    page_window = settings.PAGE_WINDOW

    (results, total_hits) = search_lucene_index(request.GET, index_dir, index_metadata, records_per_page)
    
    # Need to setup a couple variables to house the next page and previous pages (if they exist)
    # of search results, a string containing a serialized representation of our forms parameters
    # and the total number of results pages
    current_page = int(request.GET.get('page', 1))
    total_pages = ceil(float(total_hits) / records_per_page) if total_hits > 0 else 1
    page_range = get_page_range(current_page, page_window, total_pages)        

    # Get our serialized string of parameters and remove the pages var as we will set that 
    # ourselves
    params_str = request.GET.urlencode()
    params_str = params_str.replace("&page=%s" % current_page, '')

    # Now setup our next page and previous page variables if both exist
    prev_page = current_page - 1 if current_page != 1 else None
    next_page = current_page + 1 if current_page != total_pages else None

    print >> sys.stderr, len(results)

    # Setup our results bounds...
    lower_bound = 1
    upper_bound = len(results)
    if current_page > 1:
        upper_bound = min(records_per_page * current_page, total_hits)
        lower_bound = upper_bound - (len(results) - 1)
               
    template = get_template('content/search_content.html')
    variables = Context({
        'results': results,
        'page_range': xrange(page_range[0], page_range[1] + 1),
        'total_pages': int(total_pages),
        'total_hits': int(total_hits),
        'current_page': current_page,
        'previous_page': prev_page,
        'next_page': next_page,
        'lower_bound': lower_bound,
        'upper_bound': upper_bound,
        'serialized_params': params_str
    })

    output = template.render(variables)
    return HttpResponse(output)

def get_page_range(current_page, window_size, total_pages):
    """
    This function will produce a window of size defined by the window_size
    variable that can be used to present a small subset of the number of pages 
    returned from a lucene search
    """
    ne_half = floor(window_size/2)
    upper_limit = total_pages - window_size
    start = max(min(current_page - ne_half, upper_limit), 1) if current_page > ne_half else 1
    end = min(current_page + ne_half + (window_size % 2), total_pages) if current_page > ne_half else min(window_size, total_pages) 
    return [start, end]

def visualize_content(request, doid, name):
    """
    Returns a page containing a visualization of the immediate relationships
    between the specified node (doid) and its parents/children.
    """    
    template = get_template('content/visualize_content.html')
    variables = Context({
        'title': "Disease Ontology - Visulization %s" % name,
        'doid': doid,
        'name': name,
        'content_type': 'visual'
    })

    output = template.render(variables)
    return HttpResponse(output)

def validate_captcha(request, form):
    """
    Validates the captcha challenge found on the contact form
    """
    response = captcha.submit(
        request.POST.get('recaptcha_challenge_field'),
        request.POST.get('recaptcha_response_field'),
        settings.RECAPTCHA_PRIVATE_KEY,
        request.META.get('REMOTE_ADDR', None)
    )        

    return response.is_valid

@csrf_exempt
def contact(request):
    valid_captcha = True

    if request.method == "POST":
        form = ContactForm(request.POST)
        valid_captcha = validate_captcha(request, form)
    
        if form.is_valid() and valid_captcha:
            feedback_type = form.cleaned_data['feedbackType']
            sender_name = form.cleaned_data['senderName']
            sender_email = form.cleaned_data['senderEmail']
            message = form.cleaned_data['message']
            subject = "disease-ontology.org %s - %s" % (feedback_type, sender_name)

            send_mail(subject, message, sender_email, [x[1] for x in settings.ADMINS])
            return HttpResponseRedirect('/contact/thanks/')
    else:                            
        form = ContactForm()
        
    return render_to_response('support_contact.html', {
        'form': form,
        'recaptcha_pub_key': settings.RECAPTCHA_PUBLIC_KEY,
        'valid_captcha': valid_captcha,
    })

disease_ontology/disease_ontology/templates/about.html
{% extends "base_page.html" %}
{% block content %}
    <h2>Mission</h2>
    <p>The mission the Disease Ontology (DO) is to provide an open source ontology for the integration of biomedical data that is associated with human disease. DO will have a formally correct (in the ontology sense), semantically computable structure. Terms in DO will be well defined, using standard references. These terms will be linked to well-established, well-adopted terminologies that contain disease and disease-related concepts such as SNOMED (we are working with SNOMED to see if we can release SNOMED codes linked via UMLS to the community), ICD-9 and ICD-10, MeSH, and UMLS. The combination of a semantically computable structure and the external references to these terminologies will enable useful inference between disparate datasets using one or more of these standard terminologies to code disease. The Disease Ontology will be, at the end of this project, a community-driven, community-accepted ontology of diseases for clinical research and medicine inclusive of genetic, environmental and infectious diseases. The Disease Ontology will encapsulate, therefore, a comprehensive theory of disease. The design of the disease ontology will enable greater understanding of disease states by placing heritable disorders in the context of other infectious diseases and related diseases. The structure of Disease Ontology and the external references to other terminologies will enable the integration of disparate datasets through the concept of disease.</p>
    <h2>Scope</h2>
    <p>The Disease Ontology is a community driven, open source ontology that is designed to link disparate datasets through disease concepts. We will provide a computable structure of inheritable, environmental and infectious origins of human disease to facilitate the connection of genetic data, clinical data, and symptoms through the lens of human disease. We hope and anticipate that this will be useful for coupling disease concepts in model organisms to human disease concepts.
The Disease Ontology should enable the cross-walk between disease concepts, genes contributing to disease, and the 'cloud' of associated symptoms, findings and signs. The use of the disease ontology requires these connections to be done through evidence-based associations. Our understanding of disease, and the association of disease with phenotype, environment, and genetics is dynamic and a reflection of current knowledge.
The Disease Ontology is currently under review as part of the OBO Foundry review process.</p>
    
    <div id="members_list">
        <h3>PI's</h3>
        <ul class="default">
            <li class="default">Warren Kibbe - <a href="http://wiki.bioinformatics.northwestern.edu/index.php/Warren_Kibbe">NUBIC</a>, <a href="http://www.northwestern.edu/">Northwestern University</a></li>
            <li class="default">Lynn Schriml - <a href="http://www.igs.umaryland.edu">Institute for Genome Sciences</a></li>
        </ul>

        <h3>DO Team Members</h3>
        <ul class="default">
            <li class="default">Suvarna Nadendla - <a href="http://www.igs.umaryland.edu">Institute for Genome Sciences</a></li>
            <li class="default">Simon Lin - <a href="http://www.northwestern.edu/">Northwestern University</a></li>
            <li class="default">Pan Du - <a href="http://www.northwestern.edu/">Northwestern University</a></li>
            <li class="default">Gang (Gilbert Feng) - <a href="http://www.northwestern.edu/">Northwestern University</a></li>
        </ul>

        <h3>Scientific Advisory Board</h3>
        <ul class="default">
            <li class="default">Rex Chisholm - <a href="http://www.northwestern.edu/">Northwestern University</a></li>
            <li class="default">Michael Ashburner - <a href="http://www.cam.ac.uk/">University of Cambridge</a></li>
            <li class="default">Judy Blake - <a href="http://www.jax.org/">The Jackson Laboratory</a></li>
            <li class="default">Suzi Lewis - <a href="http://berkeley.edu/">University of California, Berkeley</a></li>
            <li class="default">Maryann Martone - <a href="http://www.ucsd.edu/">University of California, San Diego</a></li>
            <li class="default">Chris Mungall - <a href="http://berkeley.edu/">University of California, Berkeley</a></li>
            <li class="default">Alan Ruttenberg - <a href="http://sciencecommons.org/index.php">Science Commons</a></li>
            <li class="default">Barry Smith - <a href="http://www.buffalo.edu/">University of Buffalo, NY</a></li>
        </ul>

        <h3>Collaborators and Contributors</h3>
        <ul class="default">
            <li class="default">John Osborne - <a href="http://www.uab.edu/home/">University of Alabama at Birmingham</a></li>
            <li class="default">Wendy Wolf - <a href="http://www.northwestern.edu/">Northwestern</a></li>
            <li class="default">Maureen Smith - <a href="http://www.northwestern.edu/">Northwestern</a></li>
            <li class="default">Abel Kho - <a href="http://www.northwestern.edu/">Northwestern</a></li>
            <li class="default">Lihua (Julie) Zhu - <a href="http://www.umassmed.edu/index.aspx">University of Massachusetts Medical School</a></li>
            <li class="default">Bernard de Bono - <a href="http://www.ebi.ac.uk/">European Bioinformatics Institute</a></li>
            <li class="default">Peter Robinson - <a href="http://www.hu-berlin.de/">Humboldt-Universität</a></li>
            <li class="default">Paul Schofield - <a href="http://www.cam.ac.uk/">University of Cambridge</a></li>
            <li class="default">Janan Eppig - <a href="http://www.jax.org/">The Jackson Laboratory</a></li>
        </ul>
    </div>
{% endblock %}

disease_ontology/disease_ontology/templates/base_page.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>{{ title }}</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />

    <link rel="icon" type="image/x-icon" href="/media/images/DO_favicon.ico" />

    <!-- Some conditional stylesheeting here to deal with IE madness -->
    
    <!--[if IE]>
        <link rel="stylesheet" href="/media/css/disease_ontology.ie.css" type="text/css" media="screen,projection" />
    <![endif]-->

    <!--[if !IE]><!-->
        <link rel="stylesheet" href="/media/css/disease_ontology.css" type="text/css" media="screen,projection" />
    <!--<![endif]-->
    
    <script src="/media/javascript/jquery.js" type="text/javascript"></script>
    <script src="/media/javascript/transify.js" type="text/javascript"></script>
    <script src="/media/javascript/jquery.cookie.js" type="text/javascript"></script>
    <script src="/media/javascript/disease_ontology.js" type="text/javascript"></script>

    {% if ext %}
        <link rel="stylesheet" type="text/css" href="/media/css/jquery.toChecklist.min.css" media="screen,projection" />
        <link rel="stylesheet" type="text/css" href="/media/javascript/ext/resources/css/ext-all.css" />
        <link rel="stylesheet" type="text/css" href="/media/javascript/ext/resources/css/xtheme-gray.css" />
        <link rel="stylesheet" href="/media/css/validationEngine.jquery.css" type="text/css" media="screen,projection" />

        <script src="/media/javascript/jquery.tools.min.js" type="text/javascript"></script>
        <script src="/media/javascript/adv-search.js" type="text/javascript"></script>
        <script src="/media/javascript/luceneQueryValidator.js" type="text/javascript"></script>
        <script src="/media/javascript/jquery.validationEngine-en.js" type="text/javascript" charset="utf-8"></script>
        <script src="/media/javascript/jquery.validationEngine.js" type="text/javascript" charset="utf-8"></script>

        <script src='/media/javascript/ext/adapter/ext/ext-base.js' type='text/javascript'></script>
        <script src='/media/javascript/ext/ext-all.js' type='text/javascript'></script>
        <script src='/media/javascript/ext/examples/ux/TabCloseMenu.js' type='text/javascript'></script>
        <script type="text/javascript" src="/media/javascript/disease_ontology_ext.js"></script>
        <script type="text/javascript" src="/media/javascript/ext/ux/multidom.js"></script> 
        <script type="text/javascript" src="/media/javascript/ext/ux/uxvismode.js"></script> 
        <script type="text/javascript" src="/media/javascript/ext/ux/mif.js"></script> 
        <script type="text/javascript" src="/media/javascript/ext/ux/mifmsg.js"></script> 
    {% endif %}

    <!-- Google Analytics -->
    <script type="text/javascript">

     var _gaq = _gaq || [];
     _gaq.push(['_setAccount', 'UA-24894725-1']);
     _gaq.push(['_trackPageview']);

     (function() {
       var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
       ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
       var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
     })();

    </script>
</head>
<body>
    <div id="ie-notifications">
        <div class="warning message">
            <h3>This browser does not support visualization of term relationships on the Disease Ontology website</h3>
            <p>Please use Chrome, Safari or Firefox when using the Disease Ontology website to unlock visualization capabaility</p>
            <img id="notification-close" alt="Close notification overlay" src="/media/images/notifications-close.png" />
        </div>
    </div>
    <div id="all-wrap">
        <!-- header starts-->
        <div id="header-wrap">    
            <div id="header-photo">
                <img src="/media/images/DO_logo.jpg" alt="Disease Ontology logo"/>
            </div>                
        
            <div  id="nav">
                <ul>
                    <li><a href="{% url home %}">Home</a></li>
                    <li><a href="{% url about %}">About</a></li>    
                    <li><a href="{% url support %}">Support</a></li>
                    <li><a href="{% url downloads %}">Downloads</a></li>
                    <li><a href="{% url links %}">Links</a></li>
                </ul>    
            </div>    

            <div id="social">
                <a href="http://www.facebook.com/pages/Disease-ontology/135542593145282"><img alt="Disease Ontology Facebook Group" src="/media/images/facebook.png"/></a>
                <a href="http://twitter.com/diseaseontology"><img alt="Disease Ontology Twitter" src="/media/images/twitter.png"/></a>
                <a href="http://www.linkedin.com/groups?gid=3078180&amp;trk=anetsrch_name"><img alt="Disease Ontology LinkedIn" src="/media/images/linkedin.png"/></a>
                <div id="trans-background"></div>
            </div>
        
        <!-- header ends here -->
        </div>

        <div id="main">

            <!-- content starts -->
            <div id="content-outer" class="clear"><div id="content-wrapper">

                <div id="content"><div class="col-one">

                    {% block content %}{% endblock %}

                </div></div>

            <!-- contents end here -->
            </div></div>
        </div>
    </div>                            
    
    <!-- footer starts here -->
    <div id="footer-wrapper">


        <div id="footer-bottom">

            <p class="bottom-left">
                &nbsp; &copy;2011 - <strong><a href="http://www.igs.umaryland.edu">Institute for Genome Sciences</a> - <a href="http://www.medschool.umaryland.edu">University of Maryland School of Medicine</a></strong> &nbsp; &nbsp;
            </p>

            <p class="bottom-right" >
                <a href="{% url home %}">Home</a> |
                <a href="{% url about %}">About</a> |
                <a href="{% url support %}">Support</a> |
                <a href="{% url downloads %}">Downloads</a> |
                <a href="{% url links %}">Links</a>
            </p>

        </div>

    </div>
    <!-- footer ends here -->

</body> 
</html>

disease_ontology/disease_ontology/templates/downloads.html
{% extends "base_page.html" %}
{% block content %}
    <h2>Downloads</h2>
    <p>The Disease ontology can be downloaded using one of the following methods:</p>
    
    <h3>OBO Foundry</h3>        
    <p>The OBO Foundry host a version of the Disease Ontology less than 24 hours out of date.</p>
    <code><a href="http://www.obofoundry.org/cgi-bin/detail.cgi?id=disease_ontology">http://www.obofoundry.org/cgi-bin/detail.cgi?id=disease_ontology</a></code>

    <h3>Sourceforge</h3>
    <p>The latest and most up to date version of the Disease Ontology may be obtained from our Sourceforge site.</p>
    <code>svn checkout https://diseaseontology.svn.sourceforge.net/svnroot/diseaseontology/trunk/ diseaseontology</code>

    <p>Addtionally, the ontology may be downloaded using the Sourceforge web interface:</p>
    <code><a href="https://diseaseontology.svn.sourceforge.net/svnroot/diseaseontology/trunk/">https://diseaseontology.svn.sourceforge.net/svnroot/diseaseontology/trunk/</a></code>
{% endblock %}

disease_ontology/disease_ontology/templates/index.html
{% extends "base_page.html" %}
{% block content %}
    <form id="search" action="">
            <div id="search-bar">
                <input id="search-field" class="validate[required,funcCall[doCheckLuceneQueryValue]] search-field input" type="text" name="q" value="Search Ontology..." onfocus="if (this.value == 'Search Ontology...') {this.value = '';}" onblur="if (this.value == '') {this.value = 'Search Ontology...';}" />
                <input id="search-button" class="search-button submit-button" type="submit" value="Go »" />
                <span class="button-divider">|</span>
                <span id="adv-search-span"><a id="adv-search" rel="#adv-search-div">Advanced Search »</a></span>
            </div>

            <div id="adv-search-div" class="search-overlay">
                <a class="close" id="close_corner_button"><img alt="Close advanced search overlay" src="/media/images/close.png" /></a>
                <div id="adv-search-wrap">
                    <h2>Advanced Search</h2>

                    <div id="adv-search-fields">
                        <input type="hidden" id="adv_search_bool" name="adv_search" value="False"/>
                        
                        <label for="lucene-operator">Match: </label>
                        <select id="lucene-operator" name="operator">
                            <option value="AND">ALL</option>
                            <option value="OR">ANY</option>
                        </select>

                        <div id="search-field-container-1" class="dynamic">
                            <select id="field-combo-1" name="field-1" class="dynamic-field field-selector">
                                <option value="name" selected="selected">Name</option>
                                <option value="synonym">Synonym</option>
                                <option value="definition">Definition</option>
                                <option value="subset">Subset</option>
                                <option value="term\ id">DOID</option>
                                <option value="alt_id">Alternate ID</option>
                                <option value="xref">Xrefs</option>
                            </select>
                            <input type="text" id="field-val-1" name="value-1" value="" class="validate[required,funcCall[doCheckLuceneQueryValue]] dynamic-field field-text input" />
                            <img alt="" src="/media/images/spacer.gif" id="spacer" title="Remove Field" />
                        </div>

                    </div>
                </div>                    
                <div id="adv-search-footer">
                    <div id="add-field-container">
                        <input id="add-field" class="search-button" type="button" value="Add New Field" />
                    </div>
                    <div id="submit-cancel-buttons">
                        <input id="adv-search-submit" class="search-button submit-button" type="button" value="Go »" />
                    </div>                        
                </div>
            </div>
    </form>
    <div id="search-results"></div>
{% endblock %}                    

disease_ontology/disease_ontology/templates/support_contact.html
{% extends "base_page.html" %}
{% block content %}
    <h2>Contact</h2>
    <div id="contact-fields">
        <form method="post" action="{% url contact %}">
            {{ form.non_field_errors }}
            <div class="field-wrapper">
                <label id="label_feedback" for="id_feedbackType">Feedback Type:</label>
                <br />
                {{ form.feedbackType }}
                {{ form.feedbackType.errors }}
            </div>            
            <div class="field-wrapper">
                <label id="label_name" for="id_senderName">Name:</label>
                <br />
                {{ form.senderName }}
                {{ form.senderName.errors }}
            </div>            
            <div class="field-wrapper">
                <label id="label_email" for="id_senderEmail">Email:</label>
                <br />
                {{ form.senderEmail }}
                {{ form.senderEmail.errors }}
            </div>            
            <div class="field-wrapper">
                <label id="label_message" for="id_message">Message:</label>
                {{ form.message }}
                {{ form.message.errors }}
            </div>            

            <!-- Recaptcha code -->
            <div id="recaptcha">
                <label id="label_captcha">To prevent spam and abuse, please enter the text shown in the window below:</label>
                <script type="text/javascript"
                   src="http://www.google.com/recaptcha/api/challenge?k={{ recaptcha_pub_key }}">
                </script>
                <noscript>
                   <div id="no_js_recaptcha">
                       <object data="http://www.google.com/recaptcha/api/noscript?k={{ recaptcha_pub_key }}"
                           type="text/html" height="300" width="500"></object><br />
                       <!--[if IE]>
                      <iframe src="http://www.google.com/recaptcha/api/noscript?k={{ recaptcha_pub_key }}"
                                  height="300" width="500" frameborder="0"></iframe><br>
                       <![endif]-->                           
                       <textarea name="recaptcha_challenge_field" rows="3" cols="40">
                       </textarea>
                       <input type="hidden" name="recaptcha_response_field"
                           value="manual_challenge" />
                   </div>                           
                </noscript>
            </div>
            {% if not valid_captcha %}
                <ul id="captcha_error">
                    <li>Invalid captcha code entered.</li>
                </ul>
            {% endif %}
            
            <div>
                <input id="contact_submit" class="search-button" type="submit" value="Submit" />
            </div>                    
        </form>
    </div>
{% endblock %}

disease_ontology/disease_ontology/templates/thanks.html
{% extends "base_page.html" %}
{% block content %}
    <h2>Contact</h2>
        <div id="thanks_div">
            <p>Thank you for contacting us. Please allow 1-2 business days to receive a response.</p>
        </div>            
{% endblock %}    